# Change these first
owner: GoGipsy # Your GitHub organization or username, where this repository lives
repo: hermes-status-page # The name of this repository

sites:
  - name: Lines API
    url: prod-hermes-api.smarttravelit.com/hermes-lines/internal/health/status
    headers:
      - "x-api-key: $STATUS_PAGE_KEY"
  - name: Routes API
    url: prod-hermes-api.smarttravelit.com/hermes-routes/internal/health/status
    headers:
      - "x-api-key: $STATUS_PAGE_KEY"
  - name: Sales API
    url: prod-hermes-api.smarttravelit.com/hermes-sales/internal/health/status
    headers:
      - "x-api-key: $STATUS_PAGE_KEY"
  - name: Services API
    url: prod-hermes-api.smarttravelit.com/hermes-services/internal/health/status
    headers:
      - "x-api-key: $STATUS_PAGE_KEY"
  - name: Shared API
    url: prod-hermes-api.smarttravelit.com/hermes-shared/internal/health/status
    headers:
      - "x-api-key: $STATUS_PAGE_KEY"
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /hermes-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hermes Status Page
  introTitle: "**Hermes Status Page** - Microservices Monitoring"
  introMessage: This status page monitors the Hermes microservices **in real time**. Data is continuously updated from our [GitHub repository](https://github.com/GoGipsyy/hermes-status-page).
  navbar:
    - title: Status
      href: /hermes-status-page/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
